[workspace]

members = [
    "node",
    "tools/rocksdb-repl",
    "examples/http-ws",
    "examples/nym-api",
    "examples/cluster-http-api",
]

default-members = [
    "node",
    "examples/nym-api",
    "examples/cluster-http-api",
]

[profile.release]
#By default on Linux and macOS, symbol information is included in the compiled .elf
strip = true
#By default, Cargo specifies 16 parallel codegen units for release builds. This improves compile times, but prevents some optimizations.
#codegen-units = 1