[workspace]

members = [
    "examples/cluster-http-api",
    "examples/http-ws-sync",
    "examples/members_provider_http",
    "examples/nym-api",
    "node",
    "tools/rocksdb-repl",
    "examples/test2"
]

default-members = [
    "node",
]
