apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemera3-deployment
  labels:
    app: ephemera3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemera3
  template:
    metadata:
      labels:
        app: ephemera3
    spec:
      containers:
      - image: ephemera:latest
        imagePullPolicy: IfNotPresent
        name: ephemera
        env:
          - name: EPHEMERA_CONFIG
            value: "/config/ephemera3.toml"
          - name: PEERS_CONFIG
            value: "/config/peers.toml"
        volumeMounts:
          - mountPath: /config
            name: config
        ports:
          - containerPort: 3002
            name: protocol-port
          - containerPort: 7002
            name: http-port
      volumes:
        - name: config
          configMap:
            name: ephemera3
