apiVersion: v1
kind: Service
metadata:
  name: ephemera3
spec:
  selector:
    app: ephemera3
  type: LoadBalancer
  ports:
    - name: protocol-port-svc
      protocol: TCP
      port: 3002
      targetPort: protocol-port
    - name: http-port-svc
      protocol: TCP
      port: 7002
      targetPort: http-port
