apiVersion: v1
kind: Service
metadata:
  name: ephemera2
spec:
  selector:
    app: ephemera2
  type: LoadBalancer
  ports:
    - name: protocol-port-svc
      protocol: TCP
      port: 3001
      targetPort: protocol-port
    - name: http-port-svc
      protocol: TCP
      port: 7001
      targetPort: http-port
