apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemera1-deployment
  labels:
    app: ephemera1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemera1
  template:
    metadata:
      labels:
        app: ephemera1
    spec:
      containers:
      - image: ephemera:latest
        imagePullPolicy: IfNotPresent
        name: ephemera
        env:
          - name: EPHEMERA_CONFIG
            value: "/config/ephemera1.toml"
          - name: PEERS_CONFIG
            value: "/config/peers.toml"
        volumeMounts:
          - mountPath: /config
            name: config
        ports:
          - containerPort: 3000
            name: protocol-port
          - containerPort: 7000
            name: http-port
      volumes:
        - name: config
          configMap:
            name: ephemera1
