apiVersion: v1
kind: Service
metadata:
  name: ephemera1
spec:
  selector:
    app: ephemera1
  type: LoadBalancer
  ports:
    - name: protocol-port-svc
      protocol: TCP
      port: 3000
      targetPort: protocol-port
    - name: http-port-svc
      protocol: TCP
      port: 7000
      targetPort: http-port
